"""lxml build integration helper for Nanvix CPython."""

from __future__ import annotations

import shutil
from pathlib import Path, PurePosixPath

import sys as _sys

_sys.path.insert(0, str(Path(__file__).resolve().parent))
from _loader import load_sibling

config = load_sibling("config", __file__)

LXML_ARCHIVES: list[str] = [
    "liblxml_etree.a",
    "liblxml_elementpath.a",
]

_SETUP_LOCAL_GENERATED_MARKER = "# Generated by .nanvix/lxml.py. Do not edit by hand."
_LEGACY_LXML_MODULE_LINES: frozenset[str] = frozenset(
    {
        "_lxml_etree lxml_etree_builtin.c -llxml_etree -lxslt -lexslt -lxml2 -lz",
        "_lxml_elementpath lxml_elementpath_builtin.c -llxml_elementpath -lxml2 -lz",
    }
)


def _setup_local_body(sysroot: Path | str) -> str:
    sysroot_s = str(sysroot).replace("\\", "/")
    lib_dir = (
        PurePosixPath(sysroot_s) / "lib"
        if sysroot_s.startswith("/")
        else Path(sysroot_s) / "lib"
    )
    lib_dir_s = str(lib_dir).replace("\\", "/")
    return (
        f"{_SETUP_LOCAL_GENERATED_MARKER}\n"
        "_lxml_etree lxml_etree_builtin.c "
        f"-L{lib_dir_s} -llxml_etree -lxslt -lexslt -lxml2 -lz\n"
        "_lxml_elementpath lxml_elementpath_builtin.c "
        f"-L{lib_dir_s} -llxml_elementpath -lxml2 -lz\n"
    )


def generate_setup_local(repo_root: Path, sysroot: Path | str) -> None:
    setup_local = Path(repo_root) / "Modules" / "Setup.local"
    setup_local.write_text(_setup_local_body(sysroot), newline="\n")
    print(f"[lxml] Wrote {setup_local}")


def _is_lxml_generated_setup_local(content: str) -> bool:
    lines = content.splitlines()
    for line in lines:
        stripped = line.strip()
        if stripped:
            if stripped == _SETUP_LOCAL_GENERATED_MARKER:
                return True
            break

    active = [
        line.strip()
        for line in lines
        if line.strip() and not line.strip().startswith("#")
    ]
    return bool(active) and all(line in _LEGACY_LXML_MODULE_LINES for line in active)


def clear_generated_setup_local(repo_root: Path) -> None:
    path = Path(repo_root) / "Modules" / "Setup.local"
    if not path.is_file():
        return
    try:
        content = path.read_text()
    except OSError:
        return
    if _is_lxml_generated_setup_local(content):
        path.unlink()
        print(f"[lxml] Removed generated {path}")


def assert_lxml_archives(sysroot: Path) -> None:
    lib_dir = Path(sysroot) / "lib"
    missing = [name for name in LXML_ARCHIVES if not (lib_dir / name).is_file()]
    if missing:
        raise RuntimeError(
            f"Missing lxml static archives in {lib_dir}:\n"
            + "\n".join(f"  {name}" for name in missing)
        )


def copy_tree(src: Path, dst: Path) -> None:
    src = Path(src)
    dst = Path(dst)
    if not src.is_dir():
        raise RuntimeError(f"Required lxml runtime directory is missing: {src}")
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    print(f"[lxml] Staged {src} -> {dst}")


def stage_lxml_runtime(repo_root: Path, sysroot: Path) -> None:
    """Copy lxml Python files from buildroot into the test/package sysroot.

    Looks for lxml in ``.nanvix/buildroot/python-packages/lxml/``.
    Skips gracefully when the python-packages directory is not available.
    """
    buildroot = Path(repo_root) / ".nanvix" / "buildroot"
    lxml_src = buildroot / "python-packages" / "lxml"
    if not lxml_src.is_dir():
        print(
            f"[lxml] Staged lxml package not found at {lxml_src}; "
            "skipping runtime staging."
        )
        return

    py_lib = Path(sysroot) / "lib" / config.PYTHON_LIB_DIR
    if not py_lib.is_dir():
        raise RuntimeError(f"Python runtime library directory is missing: {py_lib}")

    copy_tree(lxml_src, py_lib / "lxml")
