# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

"""PPTX/lxml build integration helper for Nanvix CPython.

Provides helpers to:
- Build lxml + libxml2 + libxslt static archives via the shell script.
- Generate Modules/Setup.local so CPython links the lxml C extensions.
- Stage lxml, python-pptx, XlsxWriter, and PIL into the runtime sysroot.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath

import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent))
from _loader import load_sibling

config = load_sibling("config", __file__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PPTX_ENABLED_ENV = "NANVIX_PPTX"
PPTX_DISABLE_VALUE = "0"
PYTHON_PPTX_VERSION = "1.0.2"
XLSXWRITER_VERSION = "3.2.2"
TYPING_EXTENSIONS_VERSION = "4.15.0"

# Static archive filenames produced by nanvix-port/build-lxml-deps.sh.
LXML_ARCHIVES: list[str] = [
    "liblxml_etree.a",
    "liblxml_elementpath.a",
    "libxml2.a",
    "libxslt.a",
    "libexslt.a",
]

# Marker written as the first line of generated Setup.local.
# Used to distinguish pptx-generated files from user-authored ones so
# that clear_generated_setup_local() never removes user content.
_SETUP_LOCAL_GENERATED_MARKER = "# Generated by .nanvix/pptx.py. Do not edit by hand."

# Exact active (non-comment, non-blank) module lines produced by older
# versions of this integration.  Used to identify generated-lxml-only
# Setup.local files that are safe to remove even if they predate the marker.
_LEGACY_LXML_MODULE_LINES: frozenset[str] = frozenset({
    "_lxml_etree lxml_etree_builtin.c -llxml_etree -lxslt -lexslt -lxml2 -lz",
    "_lxml_elementpath lxml_elementpath_builtin.c -llxml_elementpath -lxml2 -lz",
})

# ---------------------------------------------------------------------------
# Feature flag
# ---------------------------------------------------------------------------


def enabled() -> bool:
    """Return True unless NANVIX_PPTX env var is set to '0'."""
    return os.environ.get(PPTX_ENABLED_ENV, "") != PPTX_DISABLE_VALUE


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def deps_dir(repo_root: Path) -> Path:
    """Return the pptx-deps work directory used by build-lxml-deps.sh."""
    return Path(repo_root) / ".nanvix" / "pptx-deps"


def staged_site_packages(repo_root: Path) -> Path:
    """Return the staged lxml site-packages directory produced by the shell script."""
    return deps_dir(repo_root) / "site-packages"


# ---------------------------------------------------------------------------
# Modules/Setup.local generation
# ---------------------------------------------------------------------------


def _setup_local_body(sysroot: Path | str) -> str:
    """Return Setup.local content with explicit sysroot library search path."""
    sysroot_s = str(sysroot).replace("\\", "/")
    lib_dir = (
        PurePosixPath(sysroot_s) / "lib"
        if sysroot_s.startswith("/")
        else Path(sysroot_s) / "lib"
    )
    lib_dir_s = str(lib_dir).replace("\\", "/")
    return (
        f"{_SETUP_LOCAL_GENERATED_MARKER}\n"
        "_lxml_etree lxml_etree_builtin.c "
        f"-L{lib_dir_s} -llxml_etree -lxslt -lexslt -lxml2 -lz\n"
        "_lxml_elementpath lxml_elementpath_builtin.c "
        f"-L{lib_dir_s} -llxml_elementpath -lxml2 -lz\n"
    )


def generate_setup_local(repo_root: Path, sysroot: Path | str) -> None:
    """Write Modules/Setup.local with lxml C extension link entries.

    CPython's build system reads this file during the link step so that
    _lxml_etree and _lxml_elementpath are compiled into python.elf.
    """
    setup_local = Path(repo_root) / "Modules" / "Setup.local"
    setup_local.write_text(_setup_local_body(sysroot), newline="\n")
    print(f"[pptx] Wrote {setup_local}")


def _is_pptx_generated_setup_local(content: str) -> bool:
    """Return True when *content* was produced by our PPTX integration.

    Two acceptance conditions (either is sufficient):

    1. The first non-empty line equals the generated marker — this is
       the check for files written by the current codebase.
    2. Every active (non-blank, non-comment) line is one of the known
       lxml module lines and at least one is present — this catches
       pre-marker generated files from earlier commits and any manually
       reproduced equivalent content.

    A Setup.local with any unrelated active entry is never matched.
    """
    lines = content.splitlines()

    # Condition 1: first non-empty line is the generated marker.
    for line in lines:
        stripped = line.strip()
        if stripped:
            if stripped == _SETUP_LOCAL_GENERATED_MARKER:
                return True
            break  # first non-empty line is something else — check condition 2

    # Condition 2: all active lines are exactly our known lxml module lines.
    active = [
        line.strip()
        for line in lines
        if line.strip() and not line.strip().startswith("#")
    ]
    return bool(active) and all(line in _LEGACY_LXML_MODULE_LINES for line in active)


def clear_generated_setup_local(repo_root: Path) -> None:
    """Remove Modules/Setup.local only when it was generated by pptx.py.

    Uses :func:`_is_pptx_generated_setup_local` so that both
    marker-bearing files (current codebase) and older generated files
    without the marker are removed.  A user-authored Setup.local with
    any unrelated active entry is never touched.

    Safe to call from ``clean()`` and from the disabled-PPTX path in
    ``build()``.
    """
    path = Path(repo_root) / "Modules" / "Setup.local"
    if not path.is_file():
        return
    try:
        content = path.read_text()
    except OSError:
        return
    if _is_pptx_generated_setup_local(content):
        path.unlink()
        print(f"[pptx] Removed generated {path}")


# ---------------------------------------------------------------------------
# Archive presence checks
# ---------------------------------------------------------------------------


def assert_lxml_archives(sysroot: Path) -> None:
    """Raise RuntimeError listing any missing lxml archives under sysroot/lib.

    Args:
        sysroot: Path to the Nanvix sysroot directory.

    Raises:
        RuntimeError: If one or more archives are absent.
    """
    lib_dir = Path(sysroot) / "lib"
    missing = [name for name in LXML_ARCHIVES if not (lib_dir / name).is_file()]
    if missing:
        raise RuntimeError(
            f"Missing lxml static archives in {lib_dir}:\n"
            + "\n".join(f"  {name}" for name in missing)
        )


def _lxml_archives_present(sysroot: Path) -> bool:
    """Return True when every lxml archive exists in sysroot/lib."""
    lib_dir = Path(sysroot) / "lib"
    return all((lib_dir / name).is_file() for name in LXML_ARCHIVES)


def _staged_lxml_present(repo_root: Path) -> bool:
    """Return True when the staged lxml __init__.py exists."""
    return (staged_site_packages(repo_root) / "lxml" / "__init__.py").is_file()


def _staged_runtime_present(repo_root: Path) -> bool:
    """Return True when all required PPTX runtime packages are staged."""
    staged = staged_site_packages(repo_root)
    return (
        (staged / "typing_extensions.py").is_file()
        and all(
            (staged / package / "__init__.py").is_file()
            for package in ("lxml", "pptx", "xlsxwriter")
        )
    )


# ---------------------------------------------------------------------------
# Sysroot locality check
# ---------------------------------------------------------------------------


def _sysroot_is_local(sysroot: Path) -> bool:
    """Return True when *sysroot* is an accessible local directory.

    When sysroot is a Docker-internal path that doesn't exist on the
    current host (e.g. ``/mnt/sysroot`` inside a container, or a
    WSL-style path on a Windows host), ``is_dir()`` returns False and
    the native bash build is skipped — the Docker prebuild hook in
    docker.py handles those cases instead.
    """
    return Path(sysroot).is_dir()


# ---------------------------------------------------------------------------
# Build lxml deps
# ---------------------------------------------------------------------------


def build_lxml_deps(
    repo_root: Path,
    sysroot: Path,
    toolchain: Path,
    run_fn=None,
) -> None:
    """Build lxml + libxml2 + libxslt archives and stage the Python package.

    Delegates to ``nanvix-port/build-lxml-deps.sh`` with ``NANVIX_HOME``
    and ``NANVIX_TOOLCHAIN`` environment variables set.

    Skips automatically when:
    - PPTX is disabled via env (``NANVIX_PPTX=0``).
    - All archives and the staged package are already present.
    - *sysroot* is a Docker-internal path not accessible on the host.

    Args:
        repo_root: Repository root (must be a host-local path).
        sysroot:   Nanvix sysroot.  Docker-internal paths are detected
                   and silently skipped with a warning.
        toolchain: Nanvix cross-compilation toolchain directory.
        run_fn:    Optional callable used by ZScript (*args, cwd=...,
                   env=...).  Falls back to ``subprocess.run`` when None
                   or when the callable does not accept an ``env`` kwarg.
    """
    if not enabled():
        return

    sysroot_p = Path(sysroot)
    toolchain_p = Path(toolchain)

    if _lxml_archives_present(sysroot_p) and _staged_runtime_present(repo_root):
        print("[pptx] lxml archives and runtime packages already present; skipping build.")
        return

    if not _sysroot_is_local(sysroot_p):
        print(
            f"[pptx] NOTE: sysroot '{sysroot_p}' is not accessible on this host. "
            "Skipping native lxml dep build. "
            "On Windows/Docker hosts use docker_mod.docker_build_lxml_deps() instead."
        )
        return

    script = Path(repo_root) / "nanvix-port" / "build-lxml-deps.sh"
    if not script.is_file():
        raise FileNotFoundError(
            f"[pptx] build-lxml-deps.sh not found: {script}"
        )

    build_env = {
        **os.environ,
        "NANVIX_HOME": str(sysroot_p),
        "NANVIX_TOOLCHAIN": str(toolchain_p),
    }

    cmd = ["bash", str(script)]

    print(
        f"[pptx] Building lxml deps "
        f"(NANVIX_HOME={sysroot_p}, NANVIX_TOOLCHAIN={toolchain_p})"
    )

    if run_fn is not None:
        # Attempt to use run_fn with env kwarg; fall back to subprocess.run
        # if the callable does not accept it (e.g. older ZScript versions).
        try:
            run_fn(*cmd, cwd=Path(repo_root), env=build_env)
        except TypeError:
            # run_fn did not accept env — use subprocess directly.
            subprocess.run(cmd, cwd=repo_root, env=build_env, check=True)
    else:
        subprocess.run(cmd, cwd=repo_root, env=build_env, check=True)

    stage_pure_python_packages(repo_root)


def _remove_package_artifacts(site_packages: Path, names: tuple[str, ...]) -> None:
    """Remove stale package directories/files before restaging pinned wheels."""
    for name in names:
        for path in site_packages.glob(name):
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()


def stage_pure_python_packages(repo_root: Path) -> None:
    """Stage pure-Python runtime dependencies with host pip.

    The Docker toolchain image intentionally stays minimal and may not have
    pip.  Keep this host-side and use ``--no-deps`` so pip does not overwrite
    the NanVix lxml build or the in-repo PIL shim.
    """
    if not enabled():
        return

    site_packages = staged_site_packages(repo_root)
    site_packages.mkdir(parents=True, exist_ok=True)
    _remove_package_artifacts(
        site_packages,
        (
            "pptx",
            "python_pptx-*.dist-info",
            "xlsxwriter",
            "XlsxWriter-*.dist-info",
            "typing_extensions.py",
            "typing_extensions-*.dist-info",
        ),
    )

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--disable-pip-version-check",
            "--no-cache-dir",
            "--no-deps",
            "--target",
            str(site_packages),
            f"python-pptx=={PYTHON_PPTX_VERSION}",
            f"XlsxWriter=={XLSXWRITER_VERSION}",
            f"typing-extensions=={TYPING_EXTENSIONS_VERSION}",
        ],
        cwd=repo_root,
        check=True,
    )


# ---------------------------------------------------------------------------
# Tree copy helper
# ---------------------------------------------------------------------------


def copy_tree(src: Path, dst: Path) -> None:
    """Recursively copy *src* into *dst*, replacing any previous copy."""
    src = Path(src)
    dst = Path(dst)
    if not src.is_dir():
        raise RuntimeError(f"Required PPTX runtime directory is missing: {src}")
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    print(f"[pptx] Staged {src} -> {dst}")


# ---------------------------------------------------------------------------
# Runtime staging
# ---------------------------------------------------------------------------


def stage_runtime(repo_root: Path, sysroot: Path) -> None:
    """Stage PPTX runtime Python packages into an installed sysroot."""
    if not enabled():
        return

    py_lib = Path(sysroot) / "lib" / config.PYTHON_LIB_DIR
    if not py_lib.is_dir():
        raise RuntimeError(f"Python runtime library directory is missing: {py_lib}")

    copy_tree(Path(repo_root) / "nanvix-port" / "PIL", py_lib / "PIL")

    staged = staged_site_packages(repo_root)
    for package in ("lxml", "pptx", "xlsxwriter"):
        copy_tree(staged / package, py_lib / package)
    typing_extensions = staged / "typing_extensions.py"
    if not typing_extensions.is_file():
        raise RuntimeError(f"Required PPTX runtime file is missing: {typing_extensions}")
    shutil.copy2(typing_extensions, py_lib / "typing_extensions.py")
    print(f"[pptx] Staged {typing_extensions} -> {py_lib / 'typing_extensions.py'}")


def write_smoke_script(repo_root: Path, destination: Path) -> Path:
    """Write a focused lxml/PIL/python-pptx smoke-test script."""
    del repo_root
    script = r'''
import io
import zipfile

from PIL import Image, ImageColor, ImageFont, ImageOps
from lxml import etree
from pptx import Presentation

doc = etree.fromstring(b"<root><child key='v'>text</child></root>")
assert doc.find("child").get("key") == "v"

png = (
    b"\x89PNG\r\n\x1a\n"
    b"\x00\x00\x00\rIHDR"
    + (32).to_bytes(4, "big")
    + (16).to_bytes(4, "big")
    + b"\x08\x02\x00\x00\x00"
)
img = Image.open(io.BytesIO(png))
assert img.size == (32, 16)
assert ImageColor.getrgb("#0f0") == (0, 255, 0)
assert ImageOps.exif_transpose(img) is img
assert ImageFont.truetype("missing.ttf", 12).getlength("Hello") > 0

prs = Presentation()
slide = prs.slides.add_slide(prs.slide_layouts[0])
slide.shapes.title.text = "NanVix PPTX"
buf = io.BytesIO()
prs.save(buf)
data = buf.getvalue()
assert len(data) > 1000
assert zipfile.is_zipfile(io.BytesIO(data))

print("NANVIX_PPTX_SMOKE_OK")
'''.lstrip()
    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / "test_nanvix_pptx_smoke.py"
    path.write_text(script)
    print(f"[pptx] Wrote smoke script to {path}")
    return path
