# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

"""PPTX/lxml build integration helper for Nanvix CPython.

Provides helpers to:
- Build lxml + libxml2 + libxslt static archives via the shell script.
- Generate Modules/Setup.local so CPython links the lxml C extensions.
- Stage the lxml Python package into site-packages (reserved for a later task).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PPTX_ENABLED_ENV = "NANVIX_PPTX"
PPTX_DISABLE_VALUE = "0"

# Static archive filenames produced by nanvix-port/build-lxml-deps.sh.
LXML_ARCHIVES: list[str] = [
    "liblxml_etree.a",
    "liblxml_elementpath.a",
    "libxml2.a",
    "libxslt.a",
    "libexslt.a",
]

# Marker written as the first line of generated Setup.local.
# Used to distinguish pptx-generated files from user-authored ones so
# that clear_generated_setup_local() never removes user content.
_SETUP_LOCAL_GENERATED_MARKER = "# Generated by .nanvix/pptx.py. Do not edit by hand."

# Exact active (non-comment, non-blank) module lines produced by this
# integration.  Used by both the host-side and container-side heuristics
# to identify generated-lxml-only Setup.local files that are safe to remove.
_LXML_MODULE_LINES: frozenset[str] = frozenset({
    "_lxml_etree lxml_etree_builtin.c -llxml_etree -lxslt -lexslt -lxml2 -lz",
    "_lxml_elementpath lxml_elementpath_builtin.c -llxml_elementpath -lxml2 -lz",
})

# Content written to Modules/Setup.local when PPTX is enabled.
# CPython's Makefile reads this file to link extra C extension modules.
SETUP_LOCAL_BODY: str = (
    f"{_SETUP_LOCAL_GENERATED_MARKER}\n"
    "_lxml_etree lxml_etree_builtin.c -llxml_etree -lxslt -lexslt -lxml2 -lz\n"
    "_lxml_elementpath lxml_elementpath_builtin.c -llxml_elementpath -lxml2 -lz\n"
)

# ---------------------------------------------------------------------------
# Feature flag
# ---------------------------------------------------------------------------


def enabled() -> bool:
    """Return True unless NANVIX_PPTX env var is set to '0'."""
    return os.environ.get(PPTX_ENABLED_ENV, "") != PPTX_DISABLE_VALUE


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def deps_dir(repo_root: Path) -> Path:
    """Return the pptx-deps work directory used by build-lxml-deps.sh."""
    return Path(repo_root) / ".nanvix" / "pptx-deps"


def staged_site_packages(repo_root: Path) -> Path:
    """Return the staged lxml site-packages directory produced by the shell script."""
    return deps_dir(repo_root) / "site-packages"


# ---------------------------------------------------------------------------
# Modules/Setup.local generation
# ---------------------------------------------------------------------------


def generate_setup_local(repo_root: Path) -> None:
    """Write Modules/Setup.local with lxml C extension link entries.

    CPython's build system reads this file during the link step so that
    _lxml_etree and _lxml_elementpath are compiled into python.elf.
    """
    setup_local = Path(repo_root) / "Modules" / "Setup.local"
    setup_local.write_text(SETUP_LOCAL_BODY)
    print(f"[pptx] Wrote {setup_local}")


def _is_pptx_generated_setup_local(content: str) -> bool:
    """Return True when *content* was produced by our PPTX integration.

    Two acceptance conditions (either is sufficient):

    1. The first non-empty line equals the generated marker — this is
       the check for files written by the current codebase.
    2. Every active (non-blank, non-comment) line is one of the known
       lxml module lines and at least one is present — this catches
       pre-marker generated files from earlier commits and any manually
       reproduced equivalent content.

    A Setup.local with any unrelated active entry is never matched.
    """
    lines = content.splitlines()

    # Condition 1: first non-empty line is the generated marker.
    for line in lines:
        stripped = line.strip()
        if stripped:
            if stripped == _SETUP_LOCAL_GENERATED_MARKER:
                return True
            break  # first non-empty line is something else — check condition 2

    # Condition 2: all active lines are exactly our known lxml module lines.
    active = [
        line.strip()
        for line in lines
        if line.strip() and not line.strip().startswith("#")
    ]
    return bool(active) and all(line in _LXML_MODULE_LINES for line in active)


def clear_generated_setup_local(repo_root: Path) -> None:
    """Remove Modules/Setup.local only when it was generated by pptx.py.

    Uses :func:`_is_pptx_generated_setup_local` so that both
    marker-bearing files (current codebase) and older generated files
    without the marker are removed.  A user-authored Setup.local with
    any unrelated active entry is never touched.

    Safe to call from ``clean()`` and from the disabled-PPTX path in
    ``build()``.
    """
    path = Path(repo_root) / "Modules" / "Setup.local"
    if not path.is_file():
        return
    try:
        content = path.read_text()
    except OSError:
        return
    if _is_pptx_generated_setup_local(content):
        path.unlink()
        print(f"[pptx] Removed generated {path}")


# ---------------------------------------------------------------------------
# Archive presence checks
# ---------------------------------------------------------------------------


def assert_lxml_archives(sysroot: Path) -> None:
    """Raise RuntimeError listing any missing lxml archives under sysroot/lib.

    Args:
        sysroot: Path to the Nanvix sysroot directory.

    Raises:
        RuntimeError: If one or more archives are absent.
    """
    lib_dir = Path(sysroot) / "lib"
    missing = [name for name in LXML_ARCHIVES if not (lib_dir / name).is_file()]
    if missing:
        raise RuntimeError(
            f"Missing lxml static archives in {lib_dir}:\n"
            + "\n".join(f"  {name}" for name in missing)
        )


def _lxml_archives_present(sysroot: Path) -> bool:
    """Return True when every lxml archive exists in sysroot/lib."""
    lib_dir = Path(sysroot) / "lib"
    return all((lib_dir / name).is_file() for name in LXML_ARCHIVES)


def _staged_lxml_present(repo_root: Path) -> bool:
    """Return True when the staged lxml __init__.py exists."""
    return (staged_site_packages(repo_root) / "lxml" / "__init__.py").is_file()


# ---------------------------------------------------------------------------
# Sysroot locality check
# ---------------------------------------------------------------------------


def _sysroot_is_local(sysroot: Path) -> bool:
    """Return True when *sysroot* is an accessible local directory.

    When sysroot is a Docker-internal path that doesn't exist on the
    current host (e.g. ``/mnt/sysroot`` inside a container, or a
    WSL-style path on a Windows host), ``is_dir()`` returns False and
    the native bash build is skipped — the Docker prebuild hook in
    docker.py handles those cases instead.
    """
    return Path(sysroot).is_dir()


# ---------------------------------------------------------------------------
# Build lxml deps
# ---------------------------------------------------------------------------


def build_lxml_deps(
    repo_root: Path,
    sysroot: Path,
    toolchain: Path,
    run_fn=None,
) -> None:
    """Build lxml + libxml2 + libxslt archives and stage the Python package.

    Delegates to ``nanvix-port/build-lxml-deps.sh`` with ``NANVIX_HOME``
    and ``NANVIX_TOOLCHAIN`` environment variables set.

    Skips automatically when:
    - PPTX is disabled via env (``NANVIX_PPTX=0``).
    - All archives and the staged package are already present.
    - *sysroot* is a Docker-internal path not accessible on the host.

    Args:
        repo_root: Repository root (must be a host-local path).
        sysroot:   Nanvix sysroot.  Docker-internal paths are detected
                   and silently skipped with a warning.
        toolchain: Nanvix cross-compilation toolchain directory.
        run_fn:    Optional callable used by ZScript (*args, cwd=...,
                   env=...).  Falls back to ``subprocess.run`` when None
                   or when the callable does not accept an ``env`` kwarg.
    """
    if not enabled():
        return

    sysroot_p = Path(sysroot)
    toolchain_p = Path(toolchain)

    if _lxml_archives_present(sysroot_p) and _staged_lxml_present(repo_root):
        print("[pptx] lxml archives and staged package already present; skipping build.")
        return

    if not _sysroot_is_local(sysroot_p):
        print(
            f"[pptx] NOTE: sysroot '{sysroot_p}' is not accessible on this host. "
            "Skipping native lxml dep build. "
            "On Windows/Docker hosts use docker_mod.docker_build_lxml_deps() instead."
        )
        return

    script = Path(repo_root) / "nanvix-port" / "build-lxml-deps.sh"
    if not script.is_file():
        raise FileNotFoundError(
            f"[pptx] build-lxml-deps.sh not found: {script}"
        )

    build_env = {
        **os.environ,
        "NANVIX_HOME": str(sysroot_p),
        "NANVIX_TOOLCHAIN": str(toolchain_p),
    }

    cmd = ["bash", str(script)]

    print(
        f"[pptx] Building lxml deps "
        f"(NANVIX_HOME={sysroot_p}, NANVIX_TOOLCHAIN={toolchain_p})"
    )

    if run_fn is not None:
        # Attempt to use run_fn with env kwarg; fall back to subprocess.run
        # if the callable does not accept it (e.g. older ZScript versions).
        try:
            run_fn(*cmd, cwd=Path(repo_root), env=build_env)
        except TypeError:
            # run_fn did not accept env — use subprocess directly.
            subprocess.run(cmd, cwd=repo_root, env=build_env, check=True)
    else:
        subprocess.run(cmd, cwd=repo_root, env=build_env, check=True)


# ---------------------------------------------------------------------------
# Tree copy helper
# ---------------------------------------------------------------------------


def copy_tree(src: Path, dst: Path) -> None:
    """Recursively copy *src* into *dst*, merging if *dst* already exists."""
    dst = Path(dst)
    dst.mkdir(parents=True, exist_ok=True)
    shutil.copytree(str(src), str(dst), dirs_exist_ok=True)


# ---------------------------------------------------------------------------
# Runtime staging — reserved for a later task; do not wire yet
# ---------------------------------------------------------------------------


def stage_runtime(repo_root: Path, sysroot: Path) -> None:
    """Stage the lxml Python package into the sysroot site-packages.

    NOTE: Not wired into the default build path yet.  This function is
    reserved for the runtime-staging task and must be called explicitly.
    """
    import sys as _sys

    src = staged_site_packages(repo_root) / "lxml"
    v = _sys.version_info
    python_lib = f"python{v.major}.{v.minor}"
    site_pkg = (
        Path(sysroot) / "lib" / python_lib / "site-packages" / "lxml"
    )
    copy_tree(src, site_pkg)
    print(f"[pptx] Staged lxml package to {site_pkg}")


def write_smoke_script(repo_root: Path, destination: Path) -> None:
    """Write a minimal PPTX smoke-test script.

    NOTE: Not wired into the default build path yet.  Reserved for the
    smoke-test task.
    """
    script = (
        "# Smoke test: verify lxml imports work in Nanvix Python.\n"
        "from lxml import etree\n"
        "doc = etree.fromstring(b'<root><child/></root>')\n"
        "assert doc.tag == 'root'\n"
        "print('lxml OK')\n"
        "try:\n"
        "    from pptx import Presentation\n"
        "    print('python-pptx OK')\n"
        "except ImportError:\n"
        "    print('python-pptx not available (expected without staged package)')\n"
    )
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script)
    print(f"[pptx] Wrote smoke script to {destination}")
